tasks:
  - name: Start web server
    before: |
      export PATH="./build/tools/:$PATH"
    init: |
      mkdir -p build/tools
      cd build/tools
      curl -O -L https://github.com/rust-lang/mdBook/releases/download/v0.4.21/mdbook-v0.4.21-x86_64-unknown-linux-gnu.tar.gz
      tar xf mdbook-v0.4.21-x86_64-unknown-linux-gnu.tar.gz
      curl -O -L https://github.com/badboy/mdbook-toc/releases/download/0.9.0/mdbook-toc-0.9.0-x86_64-unknown-linux-gnu.tar.gz
      tar xf mdbook-toc-0.9.0-x86_64-unknown-linux-gnu.tar.gz
      curl -O -L https://github.com/badboy/mdbook-open-on-gh/releases/download/2.2.0/mdbook-open-on-gh-2.2.0-x86_64-unknown-linux-gnu.tar.gz
      tar xf mdbook-open-on-gh-2.2.0-x86_64-unknown-linux-gnu.tar.gz
      cd ../..
    command: |
      mdbook serve src --dest-dir ../build/gh-pages -p 3000
ports:
  - port: 3000
    onOpen: open-preview
