[book]
authors = ["macmarrum", "dpolivaev"]
language = "en"
multilingual = false
src = "docs"
title = "Freeplane Documentation"
[output.html.fold]
enable = true
[preprocessor.toc]
command = "mdbook-toc"
renderer = ["html"]
max-level = 4
[preprocessor.open-on-gh]
command = "mdbook-open-on-gh"
renderer = ["html"]
[output.html]
# Required: Your repository URL used in the link.
git-repository-url = "https://github.com/freeplane/docs"

# Your git branch. Defaults to `main`
git-branch = "main"

# The text to use in the footer.
# The link text is marked by `[]`
open-on-text = "Found a mistake? [Edit this page on GitHub.]"
additional-css = ["open-in.css"]
